name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    
    - name: Sonar Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag trituong/user-service:v${{ github.run_number }} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Publish Image to Docker Hub
      run: docker push trituong/user-service:v${{ github.run_number }}
